"""empty message

Revision ID: 46fe54f5cebb
Revises: 63ce3f3a58c7
Create Date: 2021-03-30 00:05:58.695506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46fe54f5cebb'
down_revision = '63ce3f3a58c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('completed_task',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('task_empl', schema=None) as batch_op:
        batch_op.alter_column('empl_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('task_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_empl', schema=None) as batch_op:
        batch_op.alter_column('task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('empl_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('completed_task',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
