"""empty message

Revision ID: 8f6ce9ccbf79
Revises: 0577cec7bdd4
Create Date: 2021-04-13 17:04:37.340455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f6ce9ccbf79'
down_revision = '0577cec7bdd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=60), nullable=False))
        batch_op.drop_column('password_db')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_db', sa.VARCHAR(length=60), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
